title: SeaHUG
long_title: Seattle Area Haskell Users' Group
description: Agendas and minutes of SeaHUG monthly meetings
author: Various authors
layouts_dir: _layouts
excerpt_separator: <!--more-->
plugins:
- jekyll-gist
